#!/bin/bash
# Drop privileges to the `app` user after fixing up the docker socket group
# and a usable PATH for sparkrun / ssh / docker.
set -e

if [ -S /var/run/docker.sock ]; then
  SOCK_GID=$(stat -c "%g" /var/run/docker.sock)
  if [ -n "$SOCK_GID" ] && [ "$SOCK_GID" != "0" ]; then
    if ! getent group "$SOCK_GID" >/dev/null; then
      groupadd -g "$SOCK_GID" docker-host
    fi
    GROUP_NAME=$(getent group "$SOCK_GID" | head -n1 | cut -d: -f1)
    usermod -aG "$GROUP_NAME" app
  fi
fi

# Ensure sparkrun knows the host user for SSH.
if [ -n "${HOST_USER}" ] && [ "${HOST_USER}" != "app" ]; then
  SPARKRUN_CONFIG="$HOME/.config/sparkrun/config.yaml"
  mkdir -p "$(dirname "$SPARKRUN_CONFIG")"
  if ! grep -qE "^ssh:[[:space:]]*$" "$SPARKRUN_CONFIG" 2>/dev/null; then
    printf "\nssh:\n  user: %s\n" "$HOST_USER" >> "$SPARKRUN_CONFIG"
  fi
fi

# Shadow the bind-mounted shim at /usr/local/bin/sparkrun (whose shebang
# points to the host's uv-managed Python interpreter, not present here)
# with a wrapper using the container's Python + PYTHONPATH=site-packages.
WRAPPER=/usr/local/sbin/sparkrun
mkdir -p "$(dirname "$WRAPPER")"

SPARKRUN_SITE=""
if [ -x /usr/local/bin/sparkrun ]; then
  for candidate in /home/*/.local/share/uv/tools/sparkrun; do
    if [ -d "$candidate/lib" ]; then
      found="$(find "$candidate/lib" -maxdepth 2 -name 'site-packages' -type d 2>/dev/null | head -1)"
      if [ -n "$found" ] && [ -d "$found/sparkrun" ]; then
        SPARKRUN_SITE="$found"
        break
      fi
    fi
  done
fi

if [ -z "$SPARKRUN_SITE" ]; then
  echo 'ERROR: sparkrun venv site-packages not found — invocations will fail.' >&2
  cat > "$WRAPPER" <<EOF
#!/bin/bash
echo 'ERROR: sparkrun venv site-packages not found' >&2
exit 127
EOF
  chmod 0755 "$WRAPPER"
else
  cat > "$WRAPPER" <<EOF
#!/bin/bash
exec /usr/local/bin/python -c "import sys, runpy; sys.path.insert(0, '$SPARKRUN_SITE'); runpy.run_module('sparkrun', run_name='__main__')" "\$@"
EOF
  chmod 0755 "$WRAPPER"
fi

# Export PATH before dropping to `app`; otherwise ssh/docker/monitor all fail (#122).
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
APP_PROFILE=/etc/profile.d/sparkrun-ui.sh
{
  echo '# Generated by docker/entrypoint.sh — do not edit.'
  echo "export PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\${PATH:+:\$PATH}\""
} > "$APP_PROFILE"
chmod 0644 "$APP_PROFILE"

# Auto-detect loopback: if docker socket is mounted, the app user has
# direct daemon access so set USER=$HOST_USER to make sparkrun use
# local docker-exec instead of SSH'ing to itself (#122).
if [ -S /var/run/docker.sock ] && [ -n "${HOST_USER}" ] && [ "${HOST_USER}" != "app" ]; then
  export USER="${HOST_USER}"
fi

exec gosu app "$@"
